gemv_mat_vec_rel – ForMatmul
gemv_mat_vec_rel Function
Seyed Ali Ghasemi
25 statements
Source File
private pure function gemv_mat_vec_rel(A, x) result(y)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), dimension(:, :), contiguous :: A
real(kind=rk), intent(in), dimension(:), contiguous :: x
Return Value real(kind=rk), dimension(size(A,1))
Called by
Contents
Source Code
gemv_mat_vec_rel
Source Code
   pure function gemv_mat_vec_rel(A, x) result(y)
      real(rk), dimension(:, :), contiguous, intent(in) :: A
      real(rk), dimension(:), contiguous, intent(in)    :: x
      real(rk), dimension(size(A,1))                    :: y
      ! real(rk), dimension(:), allocatable               :: y
      integer                                           :: m, n
      interface
         pure subroutine dgemv(f_trans, f_m, f_n, f_alpha, f_a, f_lda, f_x, f_incx, f_beta, f_y, f_incy)
            import rk
            integer,   intent(in)    :: f_m
            integer,   intent(in)    :: f_n
            integer,   intent(in)    :: f_lda
            character, intent(in)    :: f_trans
            real(rk),  intent(in)    :: f_alpha
            real(rk),  intent(in)    :: f_a(f_lda, *)
            real(rk),  intent(in)    :: f_x(*)
            integer,   intent(in)    :: f_incx
            real(rk),  intent(in)    :: f_beta
            real(rk),  intent(inout) :: f_y(*)
            integer,   intent(in)    :: f_incy
         end subroutine dgemv
      end interface
      m = size(A, 1)
      n = size(A, 2)
      call dgemv('N', m, n, 1.0_rk, A, m, x, 1, 0.0_rk, y , 1)
      !===============================================================================
   end function gemv_mat_vec_rel
Call graph
matmul_blas calls gemv_mat_vec_rel
mat_mat calls matmul_blas
mat_vec calls matmul_blas
benchmark1 calls matmul_blas
benchmark2 calls matmul_blas
example5 calls matmul_blas
example7 calls matmul_blas
matmul calls mat_mat, mat_vec