mat_mat_rel – ForMatmul
mat_mat_rel Function
Seyed Ali Ghasemi
BSD 3-Clause
42 statements
Source File
private pure function mat_mat_rel(A, B, transA, transB, option) result(C)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: A(:,:)
real(kind=rk), intent(in), contiguous :: B(:,:)
logical, intent(in), optional :: transA
logical, intent(in), optional :: transB
character(len=*), intent(in), optional :: option
Return Value real(kind=rk), allocatable, (:,:)
Calls
Called by
Source Code
   pure function mat_mat_rel(A, B, transA, transB, option) result(C)
      real(rk), intent(in), contiguous :: A(:,:), B(:,:)
      real(rk), allocatable :: C(:,:)
      character(*), intent(in), optional :: option
      logical, intent(in), optional :: transA, transB
      if (present(transA) .and. present(transB)) then
         if (.not.transA .and. .not.transB) then
            ! AB
            allocate(C(size(A,1), size(B,2)), source=0.0_rk)
            call mat_mat_rel_AB(A, B, C, option)
         else if (transA .and. transB) then
            ! ATBT
            allocate(C(size(A,2), size(B,1)), source=0.0_rk)
            call mat_mat_rel_ATBT(A, B, C, option)
         else if (transA .and. .not.transB) then
            ! ATB
            allocate(C(size(A,2), size(B,2)), source=0.0_rk)
            call mat_mat_rel_ATB(A, B, C, option)
         else if (.not.transA .and. transB) then
            ! ABT
            allocate(C(size(A,1), size(B,1)), source=0.0_rk)
            call mat_mat_rel_ABT(A, B, C, option)
         end if
      else if (present(transA) .or. present(transB)) then
         if (present(transA)) then
            if (transA) then
               ! ATB
               allocate(C(size(A,2), size(B,2)), source=0.0_rk)
               call mat_mat_rel_ATB(A, B, C, option)
            else if (.not.transA) then
               ! ABT
               allocate(C(size(A,1), size(B,1)), source=0.0_rk)
               call mat_mat_rel_ABT(A, B, C, option)
            end if
         else if (present(transB)) then
            if (transB) then
               ! ABT
               allocate(C(size(A,1), size(B,1)), source=0.0_rk)
               call mat_mat_rel_ABT(A, B, C, option)
            else if (.not.transB) then
               ! ATB
               allocate(C(size(A,2), size(B,2)), source=0.0_rk)
               call mat_mat_rel_ATB(A, B, C, option)
            end if
         end if
      else if (.not.present(transA) .and. .not.present(transB)) then
         ! AB
         allocate(C(size(A,1), size(B,2)), source=0.0_rk)
         call mat_mat_rel_AB(A, B, C, option)
      end if
   end function mat_mat_rel
Call graph
mat_mat_rel calls mat_mat_rel_ab, mat_mat_rel_abt, mat_mat_rel_atb, mat_mat_rel_atbt
mat_mat_rel_ab calls mat_mat_rel_ab_opt
mat_mat_rel_abt calls mat_mat_rel_abt_opt
mat_mat_rel_atb calls mat_mat_rel_atb_opt
mat_mat_rel_atbt calls mat_mat_rel_atbt_opt
mat_mat_rel_ab_opt calls mm_ab_1, mm_ab_10, mm_ab_11, mm_ab_12, mm_ab_13, mm_ab_2, mm_ab_3, mm_ab_4, mm_ab_5, mm_ab_6, mm_ab_7, mm_ab_8, mm_ab_9
mat_mat_rel_abt_opt calls mm_abt_1, mm_abt_10, mm_abt_11, mm_abt_12, mm_abt_13, mm_abt_2, mm_abt_3, mm_abt_4, mm_abt_5, mm_abt_6, mm_abt_7, mm_abt_8, mm_abt_9
mat_mat_rel_atb_opt calls mm_atb_1, mm_atb_10, mm_atb_11, mm_atb_12, mm_atb_13, mm_atb_2, mm_atb_3, mm_atb_4, mm_atb_5, mm_atb_6, mm_atb_7, mm_atb_8, mm_atb_9
mat_mat_rel_atbt_opt calls mm_atbt_1, mm_atbt_10, mm_atbt_11, mm_atbt_12, mm_atbt_13, mm_atbt_2, mm_atbt_3, mm_atbt_4, mm_atbt_5, mm_atbt_6, mm_atbt_7, mm_atbt_8, mm_atbt_9
mm_ab_2 calls gemm
mm_abt_2 calls gemm
mm_atb_2 calls gemm
mm_atbt_2 calls gemm
matmul calls mat_mat_rel