mat_vec – ForMatmul
mat_vec Function
36 statements
Source File
private pure function mat_vec(A, v, method, option) result(w)
Matrix-vector multiplication using coarray parallelism. author: Seyed Ali Ghasemi
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: A(:,:)
Input matrix A and vector v.
real(kind=rk), intent(in), contiguous :: v(:)
Input matrix A and vector v.
character(len=*), intent(in) :: method
Multiplication method ('coarray').
character(len=*), intent(in), optional :: option
Optional method-specific option.
Return Value real(kind=rk), allocatable, (:)
Result vector w.
Calls
Called by
Contents
Source Code
mat_vec
Source Code
   pure function mat_vec(A, v, method, option) result(w)
      !> Input matrix A and vector v.
      real(rk),     intent(in), contiguous :: A(:,:), v(:)
      !> Multiplication method ('coarray').
      character(*), intent(in)             :: method
      !> Optional method-specific option.
      character(*), intent(in), optional   :: option
      !> Result vector w.
      real(rk), allocatable                :: w(:)
      if (method == 'coarray') then
         ! Coarray-based parallel multiplication.
         block
            integer               :: i, block_size, n, im, nimg
            real(rk), allocatable :: w_block(:)[:]
            integer               :: m, remainder_m
            im          = this_image()
            nimg        = num_images()
            m           = size(A, 1)
            n           = size(A, 2)
            block_size  = m/nimg
            remainder_m = m - block_size * (nimg - 1)
            if (mod(m, nimg) == 0) then
               if (.not. allocated(w_block)) allocate(w_block(block_size)[*])
               w_block(:) = matmul_opts(A((im-1)*block_size + 1 : im*block_size, 1:n), v, option)
            else
               if (.not. allocated(w_block)) allocate(w_block(remainder_m)[*])
               w_block(:) = matmul_opts(A((im-1)*block_size + 1 : im*block_size + remainder_m, 1:n), v, option)
            end if
            sync all
            ! critical
            if (im == 1) then
               if (.not. allocated(w)) allocate(w(m))
               do i = 1, nimg - 1
                  w((i-1)*block_size + 1 : i*block_size) = w_block(:)[i]
               end do
               w((nimg-1)*block_size + 1 : m) = w_block(:)[nimg]
            end if
            ! end critical
         end block
      else
         ! Unsupported multiplication method.
         error stop 'Error: The specified method is not available for matrix-vector multiplication!'
         ! if (this_image() == 1) then
         !    ! if (.not. allocated(w)) allocate(w(m))
         !    w = matmul(A, v)
         ! end if
      end if
   end function mat_vec
Call graph
mat_vec calls matmul_opts, w_block
matmul_opts calls matmul_mat_mat_rel_opts, matmul_mat_vec_rel_opts
matmul_mat_mat_rel_opts calls matmul_blas, mm_10, mm_11, mm_9, mm_mnp, mm_mpn, mm_nmp, mm_npm, mm_pmn, mm_pnm
matmul_mat_vec_rel_opts calls matmul_blas
matmul_blas calls gemm_mat_mat_rel, gemv_mat_vec_rel
matmul calls mat_vec