mat_vec_rel_Av – ForMatmul
mat_vec_rel_Av Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
10 statements
Source File
private pure subroutine mat_vec_rel_Av(A, v, w, option)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: A(:,:)
real(kind=rk), intent(in), contiguous :: v(:)
real(kind=rk), intent(inout), contiguous :: w(:)
character(len=*), intent(in), optional :: option
Calls
Called by
Source Code
   pure subroutine mat_vec_rel_Av(A, v, w, option)
      real(rk), intent(in), contiguous :: A(:,:), v(:)
      real(rk), intent(inout), contiguous :: w(:)
      character(*), intent(in), optional :: option
      if (present(option)) then
         call mat_vec_rel_Av_opt(A, v, w, option)
      else
         call mat_vec_rel_Av_opt(A, v, w, 'm2')
      end if
   end subroutine mat_vec_rel_Av
Call graph
mat_vec_rel_av calls mat_vec_rel_av_opt
mat_vec_rel_av_opt calls mv_av_1, mv_av_2, mv_av_3, mv_av_4, mv_av_5, mv_av_6, mv_av_7, mv_av_8
mv_av_2 calls gemv
mat_vec_rel calls mat_vec_rel_av
matmul calls mat_vec_rel