mat_vec_rel_ATv_opt – ForMatmul
mat_vec_rel_ATv_opt Subroutine
Seyed Ali Ghasemi
23 statements
Source File
public pure subroutine mat_vec_rel_ATv_opt(A, v, w, option)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: A(:,:)
real(kind=rk), intent(in), contiguous :: v(:)
real(kind=rk), intent(inout), contiguous :: w(:)
character(len=*), intent(in) :: option
Calls
Called by
Source Code
   pure subroutine mat_vec_rel_ATv_opt(A, v, w, option)
      real(rk), intent(in), contiguous :: A(:,:), v(:)
      real(rk), intent(inout), contiguous :: w(:)
      character(*), intent(in) :: option
      select case (option)
       case ('m1')
         call mv_ATv_1(A, v, w)
       case ('m2')
         call mv_ATv_2(A, v, w)
       case ('m3')
         call mv_ATv_3(A, v, w)
       case ('m4')
         call mv_ATv_4(A, v, w)
       case ('m5')
         call mv_ATv_5(A, v, w)
       case ('m6')
         call mv_ATv_6(A, v, w)
       case ('m7')
         call mv_ATv_7(A, v, w)
       case ('m8')
         call mv_ATv_8(A, v, w)
      end select
   end subroutine mat_vec_rel_ATv_opt
Call graph
mat_vec_rel_atv_opt calls mv_atv_1, mv_atv_2, mv_atv_3, mv_atv_4, mv_atv_5, mv_atv_6, mv_atv_7, mv_atv_8
mv_atv_2 calls gemv
mat_vec_rel_atv calls mat_vec_rel_atv_opt
mat_vec_rel calls mat_vec_rel_atv
matmul calls mat_vec_rel