mat_mat – ForMatmul
mat_mat Function
Seyed Ali Ghasemi
83 statements
Source File
private pure function mat_mat(A, B, method, option) result(C)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: A(:,:)
real(kind=rk), intent(in), contiguous :: B(:,:)
character(len=*), intent(in) :: method
character(len=*), intent(in), optional :: option
Return Value real(kind=rk), (size(A,1),size(B,2))
Calls
Called by
Contents
Source Code
mat_mat
Source Code
   pure function mat_mat(A, B, method, option) result(C)
      real(rk),     intent(in), contiguous :: A(:,:), B(:,:)
      character(*), intent(in)             :: method
      character(*), intent(in), optional   :: option
      ! real(rk), allocatable                :: C(:,:)
      real(rk)                             :: C(size(A,1),size(B,2))
      if (method == 'coarray') then
         if (size(A,1) >= size(B,2)) then
            block
               integer               :: i, block_size, n, im, nimg
               real(rk), allocatable :: C_block(:,:)[:]
               integer               :: m, o, remainder_m
               real(rk), allocatable :: A_block(:,:)
               im          = this_image()
               nimg        = num_images()
               m           = size(A,1)
               o           = size(B,2)
               n           = size(A,2)
               block_size  = m/nimg
               if ( mod(m, nimg) == 0 ) then
                  if (.not. allocated(C_block)) allocate(C_block(block_size, o)[*])
                  A_block = A((im-1)*block_size + 1 : im*block_size, :)
               else
                  remainder_m = m - block_size * (nimg - 1)
                  if (.not. allocated(C_block)) allocate(C_block(remainder_m, m)[*])
                  A_block = A((im-1)*block_size + 1 : im*block_size + remainder_m, :)
               end if
               select case (option)
                  case ('matmul')
                  C_block(:, :)[im] = matmul(A_block, B)
                  case ('blas')
                  C_block(:, :)[im] = matmul_blas(A_block, B)
                  case default
                  C_block(:, :)[im] = matmul(A_block, B)
               end select
               sync all
               ! critical
               if (im == 1) then
                  ! if (.not. allocated(C)) allocate(C(m, o))
                  do i = 1, nimg - 1
                     C((i-1)*block_size + 1 : i*block_size, :) = C_block(:,:)[i]
                  end do
                  C((nimg-1)*block_size + 1 : m, :) = C_block(:,:)[nimg]
               end if
               ! end critical
            end block
         else
            block
               integer               :: i, block_size, n, im, nimg
               real(rk), allocatable :: C_block(:,:)[:]
               integer               :: m, o, remainder_m
               real(rk), allocatable :: B_block(:,:)
               im          = this_image()
               nimg        = num_images()
               m           = size(A,1)
               o           = size(B,2)
               n           = size(A,2)
               block_size  = o/nimg
               if ( mod(o, nimg) == 0 ) then
                  if (.not. allocated(C_block)) allocate(C_block(m, block_size)[*])
                  B_block = B(:, (im-1)*block_size + 1 : im*block_size)
               else
                  remainder_m = o - block_size * (nimg - 1)
                  if (.not. allocated(C_block)) allocate(C_block(m, remainder_m)[*])
                  B_block = B(:, (im-1)*block_size + 1 : im*block_size + remainder_m)
               end if
               select case (option)
                  case ('matmul')
                  C_block(:, :)[im] = matmul(A, B_block)
                  case ('blas')
                  C_block(:, :)[im] = matmul_blas(A, B_block)
                  case default
                  C_block(:, :)[im] = matmul(A, B_block)
               end select
               sync all
               ! critical
               if (im == 1) then
                  ! if (.not. allocated(C)) allocate(C(m, o))
                  do i = 1, nimg - 1
                     C(:, (i-1)*block_size + 1 : i*block_size) = C_block(:,:)[i]
                  end do
                  C(:, (nimg-1)*block_size + 1 : o) = C_block(:,:)[nimg]
               end if
               ! end critical
            end block
         end if
      else
         error stop 'Error: The specified method is not available for matrix-matrix multiplication!'
         ! if (this_image() == 1) then
         !    ! if (.not. allocated(C)) allocate(C(m, o))
         !    C = matmul(A, B)
         ! end if
      end if
   end function mat_mat
Call graph
mat_mat calls a_block, b_block, c_block, matmul_blas
matmul_blas calls gemm_mat_mat_rel, gemv_mat_vec_rel
matmul calls mat_mat