mat_mat_rel_ABT – ForMatmul
mat_mat_rel_ABT Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
10 statements
Source File
private pure subroutine mat_mat_rel_ABT(A, B, C, option)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: A(:,:)
real(kind=rk), intent(in), contiguous :: B(:,:)
real(kind=rk), intent(inout), contiguous :: C(:,:)
character(len=*), intent(in), optional :: option
Calls
Called by
Source Code
   pure subroutine mat_mat_rel_ABT(A, B, C, option)
      real(rk), intent(in), contiguous :: A(:,:), B(:,:)
      real(rk), intent(inout), contiguous :: C(:,:)
      character(*), intent(in), optional :: option
      if (present(option)) then
         call mat_mat_rel_ABT_opt(A, B, C, option)
      else
         call mat_mat_rel_ABT_opt(A, B, C, 'm2')
      end if
   end subroutine mat_mat_rel_ABT
Call graph
mat_mat_rel_abt calls mat_mat_rel_abt_opt
mat_mat_rel_abt_opt calls mm_abt_1, mm_abt_10, mm_abt_11, mm_abt_12, mm_abt_13, mm_abt_2, mm_abt_3, mm_abt_4, mm_abt_5, mm_abt_6, mm_abt_7, mm_abt_8, mm_abt_9
mm_abt_2 calls gemm
mat_mat_rel calls mat_mat_rel_abt
matmul calls mat_mat_rel