mat_mat_rel_ATB – ForMatmul
mat_mat_rel_ATB Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
10 statements
Source File
private pure subroutine mat_mat_rel_ATB(A, B, C, option)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: A(:,:)
real(kind=rk), intent(in), contiguous :: B(:,:)
real(kind=rk), intent(inout), contiguous :: C(:,:)
character(len=*), intent(in), optional :: option
Calls
Called by
Source Code
   pure subroutine mat_mat_rel_ATB(A, B, C, option)
      real(rk), intent(in), contiguous :: A(:,:), B(:,:)
      real(rk), intent(inout), contiguous :: C(:,:)
      character(*), intent(in), optional :: option
      if (present(option)) then
         call mat_mat_rel_ATB_opt(A, B, C, option)
      else
         call mat_mat_rel_ATB_opt(A, B, C, 'm2')
      end if
   end subroutine mat_mat_rel_ATB
Call graph
mat_mat_rel_atb calls mat_mat_rel_atb_opt
mat_mat_rel_atb_opt calls mm_atb_1, mm_atb_10, mm_atb_11, mm_atb_12, mm_atb_13, mm_atb_2, mm_atb_3, mm_atb_4, mm_atb_5, mm_atb_6, mm_atb_7, mm_atb_8, mm_atb_9
mm_atb_2 calls gemm
mat_mat_rel calls mat_mat_rel_atb
matmul calls mat_mat_rel