mat_vec_rel – ForMatmul
mat_vec_rel Function
Seyed Ali Ghasemi
BSD 3-Clause
18 statements
Source File
private pure function mat_vec_rel(A, v, transA, option) result(w)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: A(:,:)
real(kind=rk), intent(in), contiguous :: v(:)
logical, intent(in), optional :: transA
character(len=*), intent(in), optional :: option
Return Value real(kind=rk), allocatable, (:)
Calls
Called by
Source Code
   pure function mat_vec_rel(A, v, transA, option) result(w)
      real(rk), intent(in), contiguous :: A(:,:), v(:)
      real(rk), allocatable :: w(:)
      character(*), intent(in), optional :: option
      logical, intent(in), optional :: transA
      if (present(transA)) then
         if (transA) then
            ! ATv
            allocate(w(size(A,2)), source=0.0_rk)
            call mat_vec_rel_ATv(A, v , w, option)
         else if (.not. transA) then
            ! Av
            allocate(w(size(A,1)), source=0.0_rk)
            call mat_vec_rel_Av(A, v, w, option)
         end if
      else if (.not. present(transA)) then
         ! Av
         allocate(w(size(A,1)), source=0.0_rk)
         call mat_vec_rel_Av(A, v, w, option)
      end if
   end function mat_vec_rel
Call graph
mat_vec_rel calls mat_vec_rel_atv, mat_vec_rel_av
mat_vec_rel_atv calls mat_vec_rel_atv_opt
mat_vec_rel_av calls mat_vec_rel_av_opt
mat_vec_rel_atv_opt calls mv_atv_1, mv_atv_2, mv_atv_3, mv_atv_4, mv_atv_5, mv_atv_6, mv_atv_7, mv_atv_8
mat_vec_rel_av_opt calls mv_av_1, mv_av_2, mv_av_3, mv_av_4, mv_av_5, mv_av_6, mv_av_7, mv_av_8
mv_atv_2 calls gemv
mv_av_2 calls gemv
matmul calls mat_vec_rel