mat_mat_rel_ATBT_opt – ForMatmul
mat_mat_rel_ATBT_opt Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
33 statements
Source File
public pure subroutine mat_mat_rel_ATBT_opt(A, B, C, option)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: A(:,:)
real(kind=rk), intent(in), contiguous :: B(:,:)
real(kind=rk), intent(inout), contiguous :: C(:,:)
character(len=*), intent(in) :: option
Calls
Called by
Source Code
   pure subroutine mat_mat_rel_ATBT_opt(A, B, C, option)
      real(rk), intent(in), contiguous :: A(:,:), B(:,:)
      real(rk), intent(inout), contiguous :: C(:,:)
      character(*), intent(in) :: option
      select case (option)
       case ('m1')
         call mm_ATBT_1(A, B, C)
       case ('m2')
         call mm_ATBT_2(A, B, C)
       case ('m3')
         call mm_ATBT_3(A, B, C)
       case ('m4')
         call mm_ATBT_4(A, B, C)
       case ('m5')
         call mm_ATBT_5(A, B, C)
       case ('m6')
         call mm_ATBT_6(A, B, C)
       case ('m7')
         call mm_ATBT_7(A, B, C)
       case ('m8')
         call mm_ATBT_8(A, B, C)
       case ('m9')
         call mm_ATBT_9(A, B, C)
       case ('m10')
         call mm_ATBT_10(A, B, C)
       case ('m11')
         call mm_ATBT_11(A, B, C)
       case ('m12')
         call mm_ATBT_12(A, B, C)
       case ('m13')
         call mm_ATBT_13(A, B, C)
      end select
   end subroutine mat_mat_rel_ATBT_opt
Call graph
mat_mat_rel_atbt_opt calls mm_atbt_1, mm_atbt_10, mm_atbt_11, mm_atbt_12, mm_atbt_13, mm_atbt_2, mm_atbt_3, mm_atbt_4, mm_atbt_5, mm_atbt_6, mm_atbt_7, mm_atbt_8, mm_atbt_9
mm_atbt_2 calls gemm
mat_mat_rel_atbt calls mat_mat_rel_atbt_opt
mat_mat_rel calls mat_mat_rel_atbt
matmul calls mat_mat_rel