mat_mat_rel_ATBT – ForMatmul
mat_mat_rel_ATBT Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
10 statements
Source File
private pure subroutine mat_mat_rel_ATBT(A, B, C, option)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: A(:,:)
real(kind=rk), intent(in), contiguous :: B(:,:)
real(kind=rk), intent(inout), contiguous :: C(:,:)
character(len=*), intent(in), optional :: option
Calls
Called by
Source Code
   pure subroutine mat_mat_rel_ATBT(A, B, C, option)
      real(rk), intent(in), contiguous :: A(:,:), B(:,:)
      real(rk), intent(inout), contiguous :: C(:,:)
      character(*), intent(in), optional :: option
      if (present(option)) then
         call mat_mat_rel_ATBT_opt(A, B, C, option)
      else
         call mat_mat_rel_ATBT_opt(A, B, C, 'm2')
      end if
   end subroutine mat_mat_rel_ATBT
Call graph
mat_mat_rel_atbt calls mat_mat_rel_atbt_opt
mat_mat_rel_atbt_opt calls mm_atbt_1, mm_atbt_10, mm_atbt_11, mm_atbt_12, mm_atbt_13, mm_atbt_2, mm_atbt_3, mm_atbt_4, mm_atbt_5, mm_atbt_6, mm_atbt_7, mm_atbt_8, mm_atbt_9
mm_atbt_2 calls gemm
mat_mat_rel calls mat_mat_rel_atbt
matmul calls mat_mat_rel