mat_mat_rel_AB – ForMatmul
mat_mat_rel_AB Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
10 statements
Source File
private pure subroutine mat_mat_rel_AB(A, B, C, option)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: A(:,:)
real(kind=rk), intent(in), contiguous :: B(:,:)
real(kind=rk), intent(inout), contiguous :: C(:,:)
character(len=*), intent(in), optional :: option
Calls
Called by
Source Code
   pure subroutine mat_mat_rel_AB(A, B, C, option)
      real(rk), intent(in), contiguous :: A(:,:), B(:,:)
      real(rk), intent(inout), contiguous :: C(:,:)
      character(*), intent(in), optional :: option
      if (present(option)) then
         call mat_mat_rel_AB_opt(A, B, C, option)
      else
         call mat_mat_rel_AB_opt(A, B, C, 'm2')
      end if
   end subroutine mat_mat_rel_AB
Call graph
mat_mat_rel_ab calls mat_mat_rel_ab_opt
mat_mat_rel_ab_opt calls mm_ab_1, mm_ab_10, mm_ab_11, mm_ab_12, mm_ab_13, mm_ab_2, mm_ab_3, mm_ab_4, mm_ab_5, mm_ab_6, mm_ab_7, mm_ab_8, mm_ab_9
mm_ab_2 calls gemm
mat_mat_rel calls mat_mat_rel_ab
matmul calls mat_mat_rel