mat_mat_rel_ABT_opt – ForMatmul
mat_mat_rel_ABT_opt Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
33 statements
Source File
public pure subroutine mat_mat_rel_ABT_opt(A, B, C, option)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: A(:,:)
real(kind=rk), intent(in), contiguous :: B(:,:)
real(kind=rk), intent(inout), contiguous :: C(:,:)
character(len=*), intent(in) :: option
Calls
Called by
Source Code
   pure subroutine mat_mat_rel_ABT_opt(A, B, C, option)
      real(rk), intent(in), contiguous :: A(:,:), B(:,:)
      real(rk), intent(inout), contiguous :: C(:,:)
      character(*), intent(in) :: option
      select case (option)
       case ('m1')
         call mm_ABT_1(A, B, C)
       case ('m2')
         call mm_ABT_2(A, B, C)
       case ('m3')
         call mm_ABT_3(A, B, C)
       case ('m4')
         call mm_ABT_4(A, B, C)
       case ('m5')
         call mm_ABT_5(A, B, C)
       case ('m6')
         call mm_ABT_6(A, B, C)
       case ('m7')
         call mm_ABT_7(A, B, C)
       case ('m8')
         call mm_ABT_8(A, B, C)
       case ('m9')
         call mm_ABT_9(A, B, C)
       case ('m10')
         call mm_ABT_10(A, B, C)
       case ('m11')
         call mm_ABT_11(A, B, C)
       case ('m12')
         call mm_ABT_12(A, B, C)
       case ('m13')
         call mm_ABT_13(A, B, C)
      end select
   end subroutine mat_mat_rel_ABT_opt
Call graph
mat_mat_rel_abt_opt calls mm_abt_1, mm_abt_10, mm_abt_11, mm_abt_12, mm_abt_13, mm_abt_2, mm_abt_3, mm_abt_4, mm_abt_5, mm_abt_6, mm_abt_7, mm_abt_8, mm_abt_9
mm_abt_2 calls gemm
mat_mat_rel_abt calls mat_mat_rel_abt_opt
mat_mat_rel calls mat_mat_rel_abt
matmul calls mat_mat_rel