mat_vec_rel_Av_opt – ForMatmul
mat_vec_rel_Av_opt Subroutine
Seyed Ali Ghasemi
23 statements
Source File
public pure subroutine mat_vec_rel_Av_opt(A, v, w, option)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: A(:,:)
real(kind=rk), intent(in), contiguous :: v(:)
real(kind=rk), intent(inout), contiguous :: w(:)
character(len=*), intent(in) :: option
Calls
Called by
Source Code
   pure subroutine mat_vec_rel_Av_opt(A, v, w, option)
      real(rk), intent(in), contiguous :: A(:,:), v(:)
      real(rk), intent(inout), contiguous :: w(:)
      character(*), intent(in) :: option
      select case (option)
       case ('m1')
         call mv_Av_1(A, v, w)
       case ('m2')
         call mv_Av_2(A, v, w)
       case ('m3')
         call mv_Av_3(A, v, w)
       case ('m4')
         call mv_Av_4(A, v, w)
       case ('m5')
         call mv_Av_5(A, v, w)
       case ('m6')
         call mv_Av_6(A, v, w)
       case ('m7')
         call mv_Av_7(A, v, w)
       case ('m8')
         call mv_Av_8(A, v, w)
      end select
   end subroutine mat_vec_rel_Av_opt
Call graph
mat_vec_rel_av_opt calls mv_av_1, mv_av_2, mv_av_3, mv_av_4, mv_av_5, mv_av_6, mv_av_7, mv_av_8
mv_av_2 calls gemv
mat_vec_rel_av calls mat_vec_rel_av_opt
mat_vec_rel calls mat_vec_rel_av
matmul calls mat_vec_rel