mat_vec_rel_ATv – ForMatmul
mat_vec_rel_ATv Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
10 statements
Source File
private pure subroutine mat_vec_rel_ATv(A, v, w, option)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: A(:,:)
real(kind=rk), intent(in), contiguous :: v(:)
real(kind=rk), intent(inout), contiguous :: w(:)
character(len=*), intent(in), optional :: option
Calls
Called by
Source Code
   pure subroutine mat_vec_rel_ATv(A, v, w, option)
      real(rk), intent(in), contiguous :: A(:,:), v(:)
      real(rk), intent(inout), contiguous :: w(:)
      character(*), intent(in), optional :: option
      if (present(option)) then
         call mat_vec_rel_ATv_opt(A, v, w, option)
      else
         call mat_vec_rel_ATv_opt(A, v, w, 'm2')
      end if
   end subroutine mat_vec_rel_ATv
Call graph
mat_vec_rel_atv calls mat_vec_rel_atv_opt
mat_vec_rel_atv_opt calls mv_atv_1, mv_atv_2, mv_atv_3, mv_atv_4, mv_atv_5, mv_atv_6, mv_atv_7, mv_atv_8
mv_atv_2 calls gemv
mat_vec_rel calls mat_vec_rel_atv
matmul calls mat_vec_rel