matmul_mat_mat_rel_opts – ForMatmul
matmul_mat_mat_rel_opts Function
59 statements
Source File
private pure function matmul_mat_mat_rel_opts(A, B, option) result(C)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: A(:,:)
real(kind=rk), intent(in), contiguous :: B(:,:)
character(len=*), intent(in) :: option
Return Value real(kind=rk), (size(A,1),size(B,2))
Calls
Called by
Contents
Source Code
matmul_mat_mat_rel_opts
Source Code
   pure function matmul_mat_mat_rel_opts(A, B, option) result(C)
      real(rk),     intent(in), contiguous :: A(:,:), B(:,:)
      character(*), intent(in) :: option
      real(rk)                 :: C(size(A,1),size(B,2))
      integer                  :: m,n,k
      select case (option)
       case ('m1')
         C = matmul(A, B)
       case ('m2')
         C = matmul_blas(A, B)
       case('m3')
         m = size(A,1)
         n = size(B,2)
         k = size(B,1)
         call mm_mnp(m, k, n, a, b, c)
       case('m4')
         m = size(A,1)
         n = size(B,2)
         k = size(B,1)
         call mm_mpn(m, k, n, a, b, c)
       case('m5')
         m = size(A,1)
         n = size(B,2)
         k = size(B,1)
         call mm_nmp(m, k, n, a, b, c)
       case('m6')
         m = size(A,1)
         n = size(B,2)
         k = size(B,1)
         call mm_npm(m, k, n, a, b, c)
       case('m7')
         m = size(A,1)
         n = size(B,2)
         k = size(B,1)
         call mm_pmn(m, k, n, a, b, c)
       case('m8')
         m = size(A,1)
         n = size(B,2)
         k = size(B,1)
         call mm_pnm(m, k, n, a, b, c)
       case('m9')
         m = size(A,1)
         n = size(B,2)
         k = size(B,1)
         call mm_9(m, k, n, a, b, c)
       case('m10')
         m = size(A,1)
         n = size(B,2)
         k = size(B,1)
         call mm_10(m, k, n, a, b, c)
       case('m11')
         m = size(A,1)
         n = size(B,2)
         k = size(B,1)
         call mm_11(m, k, n, a, b, c)
       case default
         C = matmul(A, B)
      end select
   end function matmul_mat_mat_rel_opts
Call graph
matmul_mat_mat_rel_opts calls matmul_blas, mm_10, mm_11, mm_9, mm_mnp, mm_mpn, mm_nmp, mm_npm, mm_pmn, mm_pnm
matmul_blas calls gemm_mat_mat_rel, gemv_mat_vec_rel
matmul_opts calls matmul_mat_mat_rel_opts
mat_mat calls matmul_opts
mat_vec calls matmul_opts
matmul calls mat_mat, mat_vec