matmul_mat_vec_rel_opts – ForMatmul
matmul_mat_vec_rel_opts Function
25 statements
Source File
private pure function matmul_mat_vec_rel_opts(A, v, option) result(w)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: A(:,:)
real(kind=rk), intent(in), contiguous :: v(:)
character(len=*), intent(in) :: option
Return Value real(kind=rk), (size(A,1))
Calls
Called by
Source Code
   pure function matmul_mat_vec_rel_opts(A, v, option) result(w)
      real(rk),     intent(in), contiguous :: A(:,:), v(:)
      character(*), intent(in)             :: option
      real(rk)                             :: w(size(A,1))
      select case (option)
       case ('m1')
         w = matmul(A, v)
       case ('m2')
         w = matmul_blas(A, v)
       case('m3')
         call mv_3(size(A,1), size(A,2), A, v, w)
       case('m4')
         call mv_4(size(A,1), size(A,2), A, v, w)
       case('m5')
         call mv_5(size(A,1), size(A,2), A, v, w)
       case('m6')
         call mv_6(size(A,1), size(A,2), A, v, w)
       case('m7')
         call mv_7(size(A,1), size(A,2), A, v, w)
       case('m8')
         call mv_8(size(A,1), size(A,2), A, v, w)
       case default
         w = matmul(A, v)
      end select
   end function matmul_mat_vec_rel_opts
Call graph
matmul_mat_vec_rel_opts calls matmul_blas, mv_3, mv_4, mv_5, mv_6, mv_7, mv_8
matmul_blas calls gemm_mat_mat_rel, gemv_mat_vec_rel
mv_7 calls shared
mv_8 calls shared
matmul_opts calls matmul_mat_vec_rel_opts
mat_mat calls matmul_opts
mat_vec calls matmul_opts
matmul calls mat_mat, mat_vec