mm_9 – ForMatmul
mm_9 Subroutine
Seyed Ali Ghasemi
12 statements
Source File
private pure subroutine mm_9(m, n, p, a, b, c)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: m
integer, intent(in) :: n
integer, intent(in) :: p
real(kind=rk), intent(in) :: a(m,n)
real(kind=rk), intent(in) :: b(n,p)
real(kind=rk), intent(out) :: c(m,p)
Called by
Source Code
   pure subroutine mm_9(m, n, p, a, b, c)
      integer, intent(in) :: m, n, p
      real(rk), intent(in) :: a(m,n), b(n,p)
      real(rk), intent(out) :: c(m,p)
      integer :: i, k
      c = 0.0_rk
      do i = 1, p
         do k = 1, m
            c(k,i) = dot_product(a(k,:), b(:,i))
         end do
      end do
   end subroutine mm_9
Call graph
matmul_mat_mat_rel_opts calls mm_9
matmul_opts calls matmul_mat_mat_rel_opts
mat_mat calls matmul_opts
mat_vec calls matmul_opts
matmul calls mat_mat, mat_vec