mm_ATB_10 – ForMatmul
mm_ATB_10 Subroutine
Seyed Ali Ghasemi
9 statements
Source File
private pure subroutine mm_ATB_10(A, B, C)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: A(:,:)
real(kind=rk), intent(in), contiguous :: B(:,:)
real(kind=rk), intent(inout), contiguous :: C(:,:)
Called by
Source Code
   pure subroutine mm_ATB_10(A, B, C)
      real(rk), intent(in), contiguous :: A(:,:), B(:,:)
      real(rk), intent(inout), contiguous :: C(:,:)
      integer :: m, p
      integer :: i, k
      m = size(A,2)
      p = size(B,2)
      error stop 'ForMatMul: shared is not supported in gfortran'
      !   do concurrent (i = 1: p) shared(m, p) ! check shared variables
      !     do k = 1, m
      !         c(k,i) = dot_product(a(:,k), b(:,i))
      !     end do
      !   end do
   end subroutine mm_ATB_10
Call graph
mat_mat_rel_atb_opt calls mm_atb_10
mat_mat_rel_atb calls mat_mat_rel_atb_opt
mat_mat_rel calls mat_mat_rel_atb
matmul calls mat_mat_rel