mm_ABT_9 – ForMatmul
mm_ABT_9 Subroutine
Seyed Ali Ghasemi
13 statements
Source File
private pure subroutine mm_ABT_9(A, B, C)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: A(:,:)
real(kind=rk), intent(in), contiguous :: B(:,:)
real(kind=rk), intent(inout), contiguous :: C(:,:)
Called by
Source Code
   pure subroutine mm_ABT_9(A, B, C)
      real(rk), intent(in), contiguous :: A(:,:), B(:,:)
      real(rk), intent(inout), contiguous :: C(:,:)
      integer :: m, p
      integer :: i, k
      m = size(A,1)
      p = size(B,1)
      do i = 1, p
         do k = 1, m
            c(k,i) = dot_product(a(k,:), b(i,:))
         end do
      end do
   end subroutine mm_ABT_9
Call graph
mat_mat_rel_abt_opt calls mm_abt_9
mat_mat_rel_abt calls mat_mat_rel_abt_opt
mat_mat_rel calls mat_mat_rel_abt
matmul calls mat_mat_rel