mm_ATB_1 – ForMatmul
mm_ATB_1 Subroutine
Seyed Ali Ghasemi
5 statements
Source File
private pure subroutine mm_ATB_1(A, B, C)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: A(:,:)
real(kind=rk), intent(in), contiguous :: B(:,:)
real(kind=rk), intent(inout), contiguous :: C(:,:)
Called by
Source Code
   pure subroutine mm_ATB_1(A, B, C)
      real(rk), intent(in), contiguous :: A(:,:), B(:,:)
      real(rk), intent(inout), contiguous :: C(:,:)
      C = matmul(transpose(A), B)
   end subroutine mm_ATB_1
Call graph
mat_mat_rel_atb_opt calls mm_atb_1
mat_mat_rel_atb calls mat_mat_rel_atb_opt
mat_mat_rel calls mat_mat_rel_atb
matmul calls mat_mat_rel