mm_ATB_2 – ForMatmul
mm_ATB_2 Subroutine
Seyed Ali Ghasemi
9 statements
Source File
private pure subroutine mm_ATB_2(A, B, C)
Uses
external_interfaces_matmul
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: A(:,:)
real(kind=rk), intent(in), contiguous :: B(:,:)
real(kind=rk), intent(inout), contiguous :: C(:,:)
Calls
Called by
Source Code
   pure subroutine mm_ATB_2(A, B, C)
      use external_interfaces_matmul
      real(rk), intent(in), contiguous :: A(:,:), B(:,:)
      real(rk), intent(inout), contiguous :: C(:,:)
      integer                 :: m, n
      m = size(A, 2)
      n = size(A, 1)
      ! Call BLAS gemm subroutine for matrix-matrix multiplication.
      call gemm('T', 'N', m, size(B, 2), n, 1.0_rk, A, n, B, n, 0.0_rk, C, m)
   end subroutine mm_ATB_2
Call graph
mm_atb_2 calls gemm
mat_mat_rel_atb_opt calls mm_atb_2
mat_mat_rel_atb calls mat_mat_rel_atb_opt
mat_mat_rel calls mat_mat_rel_atb
matmul calls mat_mat_rel