mm_nmp – ForMatmul
mm_nmp Subroutine
@tyrandis
14 statements
Source File
private pure subroutine mm_nmp(m, n, p, a, b, c)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: m
integer, intent(in) :: n
integer, intent(in) :: p
real(kind=rk), intent(in) :: a(m,n)
real(kind=rk), intent(in) :: b(n,p)
real(kind=rk), intent(out) :: c(m,p)
Called by
Contents
Source Code
mm_nmp
Source Code
   pure subroutine mm_nmp(m, n, p, a, b, c)
      integer, intent(in) :: m, n, p
      real(rk), intent(in) :: a(m,n), b(n,p)
      real(rk), intent(out) :: c(m,p)
      integer :: i, j, k
      c = 0.0_rk
      do i=1,n
         do j=1,m
            do k=1,p
               c(j,k) = c(j,k) + a(j,i)*b(i,k)
            end do
         end do
      end do
   end subroutine mm_nmp
Call graph
matmul_mat_mat_rel_opts calls mm_nmp
matmul_opts calls matmul_mat_mat_rel_opts
mat_mat calls matmul_opts
mat_vec calls matmul_opts
matmul calls mat_mat, mat_vec