mv_Av_8 – ForMatmul
mv_Av_8 Subroutine
Seyed Ali Ghasemi
9 statements
Source File
private pure subroutine mv_Av_8(A, v, w)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: A(:,:)
real(kind=rk), intent(in), contiguous :: v(:)
real(kind=rk), intent(inout), contiguous :: w(:)
Called by
Source Code
   pure subroutine mv_Av_8(A, v, w)
      real(rk), intent(in), contiguous :: A(:,:), v(:)
      real(rk), intent(inout), contiguous :: w(:)
      integer :: m, n
      integer :: i, j
      m = size(A,1)
      n = size(A,2)
      error stop 'ForMatMul: shared is not supported in gfortran'
      !   do concurrent(i=1:m) shared(m, n, a, v) ! check shared variables
      !      do j=1,n
      !         w(i) = w(i) + a(i,j)*v(j)
      !      end do
      !   end do
   end subroutine mv_Av_8
Call graph
mat_vec_rel_av_opt calls mv_av_8
mat_vec_rel_av calls mat_vec_rel_av_opt
mat_vec_rel calls mat_vec_rel_av
matmul calls mat_vec_rel