start_benchmark – ForMatmul
start_benchmark Subroutine
Seyed Ali Ghasemi
12 statements
Source File
public subroutine start_benchmark(t, m, n, o, msg)
Arguments
Type Intent Optional Attributes Name
type(timer), intent(out) :: t
integer, intent(in) :: m
integer, intent(in) :: n
integer, intent(in) :: o
character(len=*), intent(in) :: msg
Calls
Called by
Source Code
   subroutine start_benchmark(t,m,n,o,msg)
      type(timer), intent(out) :: t
      character(*),intent(in)  :: msg
      integer,     intent(in)  :: m,n,o
#if defined(USE_COARRAY)
      sync all
      if (this_image() == 1) then
         print"(a,', m=',g0,', n=',g0,', o=',g0)", msg, m, n, o
      end if
      call t%timer_start()
#else
      print"(a,', m=',g0,', n=',g0,', o=',g0)", msg, m, n, o
      call t%timer_start()
#endif
   end subroutine start_benchmark
Call graph
start_benchmark calls timer_start
benchmark3 calls start_benchmark
benchmark4 calls start_benchmark