stop_benchmark2 – ForMatmul
stop_benchmark2 Subroutine
14 statements
Source File
subroutine stop_benchmark2(ti, im, s1, s2, s3, nloops, Mat, method, filename)
Arguments
Type Intent Optional Attributes Name
type(timer), intent(inout) :: ti
integer, intent(in) :: im
integer, intent(in) :: s1
integer, intent(in) :: s2
integer, intent(in) :: s3
integer, intent(in) :: nloops
real(kind=rk), intent(in) :: Mat(s1,s3)
character(len=*), intent(in) :: method
character(len=*), intent(in) :: filename
Calls
Called by
Contents
Source Code
stop_benchmark2
Source Code
   subroutine stop_benchmark2(ti,im,s1,s2,s3,nloops,Mat,method,filename)
      type(timer), intent(inout) :: ti
      integer,     intent(in)    :: im
      integer,     intent(in)    :: s1,s2,s3,nloops
      real(rk),    intent(in)    :: Mat(s1,s3)
      character(*),intent(in)    :: method
      character(*),intent(in)    :: filename
      if (this_image() == im) then
         call ti%timer_stop(message=' Elapsed time :',nloops=l)
         print'(a,f6.2,a)', ' Performance  : ', real(nloops, rk)*real(s1,rk)*real(s2,rk)*real(s3,rk)*1e-9_rk/ti%elapsed_time,' [GFLOPS]'
         print'(a)', ''
         call write_benchmark(method,s1,s2,s3,nloops,ti,num_images(),filename)
      end if
   end subroutine stop_benchmark2
Call graph
stop_benchmark2 calls write_benchmark, timer_stop
benchmark3 calls stop_benchmark2