gemm – ForMatmul
gemm Interface
BSD 3-Clause
50 statements
Source File
public interface gemm
Called by
Subroutines
private pure subroutine dgemm(f_transa, f_transb, f_m, f_n, f_k, f_alpha, f_a, f_lda, f_b, f_ldb, f_beta, f_c, f_ldc)
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: f_transa
character(len=1), intent(in) :: f_transb
integer, intent(in) :: f_m
integer, intent(in) :: f_n
integer, intent(in) :: f_k
real(kind=rk), intent(in) :: f_alpha
real(kind=rk), intent(in) :: f_a(f_lda,*)
integer, intent(in) :: f_lda
real(kind=rk), intent(in) :: f_b(f_ldb,*)
integer, intent(in) :: f_ldb
real(kind=rk), intent(in) :: f_beta
real(kind=rk), intent(inout) :: f_c(f_ldc,*)
integer, intent(in) :: f_ldc
private pure subroutine dgemm(f_transa, f_transb, f_m, f_n, f_k, f_alpha, f_a, f_lda, f_b, f_ldb, f_beta, f_c, f_ldc)
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: f_transa
character(len=1), intent(in) :: f_transb
integer, intent(in) :: f_m
integer, intent(in) :: f_n
integer, intent(in) :: f_k
real(kind=rk), intent(in) :: f_alpha
real(kind=rk), intent(in) :: f_a(f_lda,*)
integer, intent(in) :: f_lda
real(kind=rk), intent(in) :: f_b(f_ldb,*)
integer, intent(in) :: f_ldb
real(kind=rk), intent(in) :: f_beta
real(kind=rk), intent(inout) :: f_c(f_ldc,*)
integer, intent(in) :: f_ldc
private pure subroutine sgemm(f_transa, f_transb, f_m, f_n, f_k, f_alpha, f_a, f_lda, f_b, f_ldb, f_beta, f_c, f_ldc)
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: f_transa
character(len=1), intent(in) :: f_transb
integer, intent(in) :: f_m
integer, intent(in) :: f_n
integer, intent(in) :: f_k
real(kind=rk), intent(in) :: f_alpha
real(kind=rk), intent(in) :: f_a(f_lda,*)
integer, intent(in) :: f_lda
real(kind=rk), intent(in) :: f_b(f_ldb,*)
integer, intent(in) :: f_ldb
real(kind=rk), intent(in) :: f_beta
real(kind=rk), intent(inout) :: f_c(f_ldc,*)
integer, intent(in) :: f_ldc
Call graph
mm_ab_2 calls gemm
mm_abt_2 calls gemm
mm_atb_2 calls gemm
mm_atbt_2 calls gemm
mat_mat_rel_ab_opt calls mm_ab_2
mat_mat_rel_abt_opt calls mm_abt_2
mat_mat_rel_atb_opt calls mm_atb_2
mat_mat_rel_atbt_opt calls mm_atbt_2
mat_mat_rel_ab calls mat_mat_rel_ab_opt
mat_mat_rel_abt calls mat_mat_rel_abt_opt
mat_mat_rel_atb calls mat_mat_rel_atb_opt
mat_mat_rel_atbt calls mat_mat_rel_atbt_opt
mat_mat_rel calls mat_mat_rel_ab, mat_mat_rel_abt, mat_mat_rel_atb, mat_mat_rel_atbt
matmul calls mat_mat_rel