gemv – ForMatmul
gemv Interface
BSD 3-Clause
44 statements
Source File
public interface gemv
Called by
Subroutines
private pure subroutine dgemv(f_trans, f_m, f_n, f_alpha, f_a, f_lda, f_x, f_incx, f_beta, f_y, f_incy)
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: f_trans
integer, intent(in) :: f_m
integer, intent(in) :: f_n
real(kind=rk), intent(in) :: f_alpha
real(kind=rk), intent(in) :: f_a(f_lda,*)
integer, intent(in) :: f_lda
real(kind=rk), intent(in) :: f_x(*)
integer, intent(in) :: f_incx
real(kind=rk), intent(in) :: f_beta
real(kind=rk), intent(inout) :: f_y(*)
integer, intent(in) :: f_incy
private pure subroutine dgemv(f_trans, f_m, f_n, f_alpha, f_a, f_lda, f_x, f_incx, f_beta, f_y, f_incy)
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: f_trans
integer, intent(in) :: f_m
integer, intent(in) :: f_n
real(kind=rk), intent(in) :: f_alpha
real(kind=rk), intent(in) :: f_a(f_lda,*)
integer, intent(in) :: f_lda
real(kind=rk), intent(in) :: f_x(*)
integer, intent(in) :: f_incx
real(kind=rk), intent(in) :: f_beta
real(kind=rk), intent(inout) :: f_y(*)
integer, intent(in) :: f_incy
private pure subroutine sgemv(f_trans, f_m, f_n, f_alpha, f_a, f_lda, f_x, f_incx, f_beta, f_y, f_incy)
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: f_trans
integer, intent(in) :: f_m
integer, intent(in) :: f_n
real(kind=rk), intent(in) :: f_alpha
real(kind=rk), intent(in) :: f_a(f_lda,*)
integer, intent(in) :: f_lda
real(kind=rk), intent(in) :: f_x(*)
integer, intent(in) :: f_incx
real(kind=rk), intent(in) :: f_beta
real(kind=rk), intent(inout) :: f_y(*)
integer, intent(in) :: f_incy
Call graph
mv_atv_2 calls gemv
mv_av_2 calls gemv
mat_vec_rel_atv_opt calls mv_atv_2
mat_vec_rel_av_opt calls mv_av_2
mat_vec_rel_atv calls mat_vec_rel_atv_opt
mat_vec_rel_av calls mat_vec_rel_av_opt
mat_vec_rel calls mat_vec_rel_atv, mat_vec_rel_av
matmul calls mat_vec_rel