matmul_blas – ForMatmul
matmul_blas Interface
4 statements
Source File
public interface matmul_blas
Interface for BLAS-based matrix multiplication functions.
Calls
Called by
Contents
Module Procedures
gemm_mat_mat_rel gemv_mat_vec_rel
Module Procedures
private pure function gemm_mat_mat_rel(A, B) result(C)
Matrix-matrix multiplication using BLAS. author: Seyed Ali Ghasemi
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), dimension(:, :), contiguous :: A
Input matrices A and B.
real(kind=rk), intent(in), dimension(:, :), contiguous :: B
Return Value real(kind=rk), dimension(size(A,1), size(B,2))
Result matrix C.
private pure function gemv_mat_vec_rel(A, x) result(y)
Matrix-vector multiplication using BLAS. author: Seyed Ali Ghasemi
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), dimension(:, :), contiguous :: A
Input matrix A and vector x.
real(kind=rk), intent(in), dimension(:), contiguous :: x
Return Value real(kind=rk), dimension(size(A,1))
Result vector y.
Call graph
matmul_blas calls gemm_mat_mat_rel, gemv_mat_vec_rel
matmul_mat_mat_rel_opts calls matmul_blas
matmul_mat_vec_rel_opts calls matmul_blas
benchmark1 calls matmul_blas
benchmark2 calls matmul_blas
example5 calls matmul_blas
example7 calls matmul_blas
matmul_opts calls matmul_mat_mat_rel_opts, matmul_mat_vec_rel_opts
mat_mat calls matmul_opts
mat_vec calls matmul_opts
matmul calls mat_mat, mat_vec