matmul – ForMatmul
matmul Interface
BSD 3-Clause
8 statements
Source File
public interface matmul
Calls
Module Procedures
private pure function mat_mat_rel(A, B, transA, transB, option) result(C)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: A(:,:)
real(kind=rk), intent(in), contiguous :: B(:,:)
logical, intent(in), optional :: transA
logical, intent(in), optional :: transB
character(len=*), intent(in), optional :: option
Return Value real(kind=rk), allocatable, (:,:)
private pure function mat_mat_block_rel(a, b, transA, transB, option, nblock) result(c)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: a(:,:)
real(kind=rk), intent(in), contiguous :: b(:,:)
logical, intent(in), optional :: transA
logical, intent(in), optional :: transB
character(len=*), intent(in), optional :: option
integer, intent(in) :: nblock
Return Value real(kind=rk), allocatable, (:,:)
private impure function mat_mat_coarray_rel(a, b, transA, transB, option, coarray) result(c)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: a(:,:)
real(kind=rk), intent(in), contiguous :: b(:,:)
logical, intent(in), optional :: transA
logical, intent(in), optional :: transB
character(len=*), intent(in), optional :: option
logical, intent(in) :: coarray
Return Value real(kind=rk), allocatable, (:,:)
private pure function mat_vec_rel(A, v, transA, option) result(w)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: A(:,:)
real(kind=rk), intent(in), contiguous :: v(:)
logical, intent(in), optional :: transA
character(len=*), intent(in), optional :: option
Return Value real(kind=rk), allocatable, (:)
private pure function mat_vec_block_rel(A, v, transA, option, nblock) result(w)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: A(:,:)
real(kind=rk), intent(in), contiguous :: v(:)
logical, intent(in), optional :: transA
character(len=*), intent(in), optional :: option
integer, intent(in) :: nblock
Return Value real(kind=rk), allocatable, (:)
private impure function mat_vec_coarray_rel(A, v, transA, option, coarray) result(w)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: A(:,:)
real(kind=rk), intent(in), contiguous :: v(:)
logical, intent(in), optional :: transA
character(len=*), intent(in), optional :: option
logical, intent(in) :: coarray
Return Value real(kind=rk), allocatable, (:)
Call graph
matmul calls mat_mat_block_rel, mat_mat_coarray_rel, mat_mat_rel, mat_vec_block_rel, mat_vec_coarray_rel, mat_vec_rel
mat_mat_block_rel calls compute_block_ranges
mat_mat_coarray_rel calls compute_block_ranges
mat_mat_rel calls mat_mat_rel_ab, mat_mat_rel_abt, mat_mat_rel_atb, mat_mat_rel_atbt
mat_vec_block_rel calls compute_block_ranges
mat_vec_coarray_rel calls compute_block_ranges
mat_vec_rel calls mat_vec_rel_atv, mat_vec_rel_av
mat_mat_rel_ab calls mat_mat_rel_ab_opt
mat_mat_rel_abt calls mat_mat_rel_abt_opt
mat_mat_rel_atb calls mat_mat_rel_atb_opt
mat_mat_rel_atbt calls mat_mat_rel_atbt_opt
mat_vec_rel_atv calls mat_vec_rel_atv_opt
mat_vec_rel_av calls mat_vec_rel_av_opt
mat_mat_rel_ab_opt calls mm_ab_1, mm_ab_10, mm_ab_11, mm_ab_12, mm_ab_13, mm_ab_2, mm_ab_3, mm_ab_4, mm_ab_5, mm_ab_6, mm_ab_7, mm_ab_8, mm_ab_9
mat_mat_rel_abt_opt calls mm_abt_1, mm_abt_10, mm_abt_11, mm_abt_12, mm_abt_13, mm_abt_2, mm_abt_3, mm_abt_4, mm_abt_5, mm_abt_6, mm_abt_7, mm_abt_8, mm_abt_9
mat_mat_rel_atb_opt calls mm_atb_1, mm_atb_10, mm_atb_11, mm_atb_12, mm_atb_13, mm_atb_2, mm_atb_3, mm_atb_4, mm_atb_5, mm_atb_6, mm_atb_7, mm_atb_8, mm_atb_9
mat_mat_rel_atbt_opt calls mm_atbt_1, mm_atbt_10, mm_atbt_11, mm_atbt_12, mm_atbt_13, mm_atbt_2, mm_atbt_3, mm_atbt_4, mm_atbt_5, mm_atbt_6, mm_atbt_7, mm_atbt_8, mm_atbt_9
mat_vec_rel_atv_opt calls mv_atv_1, mv_atv_2, mv_atv_3, mv_atv_4, mv_atv_5, mv_atv_6, mv_atv_7, mv_atv_8
mat_vec_rel_av_opt calls mv_av_1, mv_av_2, mv_av_3, mv_av_4, mv_av_5, mv_av_6, mv_av_7, mv_av_8
mm_ab_2 calls gemm
mm_abt_2 calls gemm
mm_atb_2 calls gemm
mm_atbt_2 calls gemm
mv_atv_2 calls gemv
mv_av_2 calls gemv