matmul_opts – ForMatmul
matmul_opts Interface
4 statements
Source File
public interface matmul_opts
Calls
Called by
Module Procedures
private pure function matmul_mat_mat_rel_opts(A, B, option) result(C)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: A(:,:)
real(kind=rk), intent(in), contiguous :: B(:,:)
character(len=*), intent(in) :: option
Return Value real(kind=rk), (size(A,1),size(B,2))
private pure function matmul_mat_vec_rel_opts(A, v, option) result(w)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: A(:,:)
real(kind=rk), intent(in), contiguous :: v(:)
character(len=*), intent(in) :: option
Return Value real(kind=rk), (size(A,1))
Call graph
matmul_opts calls matmul_mat_mat_rel_opts, matmul_mat_vec_rel_opts
matmul_mat_mat_rel_opts calls matmul_blas, mm_10, mm_11, mm_12, mm_13, mm_9, mm_mnp, mm_mpn, mm_nmp, mm_npm, mm_pmn, mm_pnm
matmul_mat_vec_rel_opts calls matmul_blas, mv_3, mv_4, mv_5, mv_6, mv_7, mv_8
matmul_blas calls gemm_mat_mat_rel, gemv_mat_vec_rel
mm_10 calls shared
mm_11 calls shared
mv_7 calls shared
mv_8 calls shared
mat_mat calls matmul_opts
mat_vec calls matmul_opts
matmul calls mat_mat, mat_vec