example5 – ForMatmul
example5 Program
23 statements
Source File
Uses
formatmul_opts
kinds
fortime
Calls
Variables
Type Attributes Name Initial
real(kind=rk), allocatable :: A(:,:)
real(kind=rk), allocatable :: B(:,:)
real(kind=rk), allocatable :: C(:,:)
type(timer) :: t
integer :: m
integer :: n
integer :: o
Source Code
program example5
   use kinds,     only: rk
   use fortime,   only: timer
   use formatmul_opts, only: matmul_blas
   implicit none
   real(rk), allocatable :: A(:,:), B(:,:)
   real(rk), allocatable :: C(:,:)
   type(timer)           :: t
   integer               :: m, n, o
   ! C(m,o) = A(m,n).B(n,o)
   m = 64*2*100
   n = 16*100
   o = 64*10
   allocate(A(m,n),B(n,o))
   call random_number(A)
   call random_number(B)
#if defined(USE_COARRAY)
   sync all
   if (this_image() == 1) call t%timer_start()
      C = matmul_blas(A,B)
   if (this_image() == 1) call t%timer_stop(message=' Elapsed time (example5: mat_mat with blas):')
#else
   call t%timer_start()
      C = matmul_blas(A,B)
   call t%timer_stop(message=' Elapsed time (example5: mat_mat with blas):')
#endif
end program example5
Call graph
example5 calls matmul_blas, timer_start, timer_stop
matmul_blas calls gemm_mat_mat_rel, gemv_mat_vec_rel